import Head from "next/head";
import { Inter } from "next/font/google";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "@/lib/query";
import Product from "@/components/Product";
import { Gallery } from "@/styles/Gallery";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  //Fetch product from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;
  if (fetching) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <p>SHITsss...{error.message}</p>;
  }
  const products = data.products.data;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallery>
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>
    </>
  );
}
